### ISSUE TITLE
T3ll not loading on Windows 10

### ISSUE THREAD

**Issue by andreashager** [garfieldius/t3ll#13]
**Preconditions**

- t3ll version:  v0.6.0 (64 Bit)
- OS: Windows 10 Version 20H2 (Build 19042.746)

**Describe the bug**

When I try to  run the editor from the command line with the flag the editor does not open and nothing is shown.

**To Reproduce**

1. Download the "t3ll_windows_x64.exe" file to a directory
2. Rename it to t3ll.exe
3. Create locallang.xlf file with the following content:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
    <file source-language="en" product-name="oesv_digital_app" date="2021-02-03T11:11:07+01:00">
        <header></header>
        <body>
            <trans-unit id="validator.propertiesequal.notvalid" resname="validator.propertiesequal.notvalid">
                <source>Both values are not identical</source>
            </trans-unit>
            <trans-unit id="validator.usernameexists.notvalid" resname="validator.usernameexists.notvalid">
                <source>The email "%s" is already in use by another user</source>
            </trans-unit>
        </body>
    </file>
</xliff>
```
4. Open Powershell and type `.\t3ll.exe .\locallang.xlf` - no window is shown to translate.

**Comment by liayn** [comment]
Works for me on Windows 19042.789.
Tried with git bash and powershell.

**Comment by andreashager** [comment]
I did an Windows Update and I also have now the version 19042.789. But the problem is the same, when I start it from the command line now window with the editor pops up (see Screenshot):

![Screenshot 2021-02-08 204643](https://user-images.githubusercontent.com/3351175/107273303-27587000-6a4f-11eb-9819-5fde0a92aa78.png)

Do I miss something? Do I need some extra dependency? I tried it on two different PCs but there is the same result, the Translation Editor is not loading 😞

**Comment by liayn** [comment]
Don't know if it matters: I have Google Chrome installed too.

**Comment by andreashager** [comment]
I also have Google Chrome installed 😞 
Can i debug it somehow with any logs?

**Comment by liayn** [comment]
Okay, I'm out of real ideas... Maybe addons in Chrome?

**Comment by andreashager** [comment]
I deactivated all the Add-Ons - it still not working. Is there any log output I can activate? 😊

**Comment by garfieldius** [comment]
Could reproduce on a new Windows installations. Found out that Chrome now installs itself to `C:\Program Files\Google\Chrome\Application\chrome.exe`, was `C:\Program Files (x86)\Google\Chrome\Application\chrome.exe` before. Will add the new path to the lookup this evening and check then. Its unexpected that no error message is shown though...

**Comment by liayn** [comment]
Confirmed, my Chrome is in `C:\Program Files (x86)`

**Comment by andreashager** [comment]
@garfieldius You are right 🥳 I have a very fresh Windows Installation (2 weeks old), my Chrome is installed in the directory `C:\Program Files\Google\Chrome\Application\chrome.exe`. 

@liayn Thanks for you support 😊

**Comment by andreashager** [comment]
@garfieldius Works like a charm now, thanks for your help! 🥳
