### ISSUE TITLE
Console hangs after closing T3ll

### ISSUE THREAD

**Issue by andreashager** [garfieldius/t3ll#15]
**Preconditions**

- t3ll version: v0.6.2 (64 Bit)
- OS: Windows 10 Version 20H2 (Build 19042.870)

**Describe the bug**

When I run the editor from the command line and close it after changes are finished the console hangs and I could not type anything more in the console.

**To Reproduce**

1. Download the "t3ll_windows_x64.exe" file to a directory
2. Rename it to t3ll.exe
3. Open any locallang.xlf file from Windows Console/Terminal
4. Change same fields or close the t3ll Editor directly.
5. Terminal hangs and waiting to complete.
6. You have to close the Terminal and reopen it after editing the language strings.

**Screenshots**
![terminal-hangs](https://user-images.githubusercontent.com/3351175/113818884-c6ac9180-9778-11eb-9c9e-d1e26a0814e1.png)

**Comment by liayn** [comment]
I had this issue randomly in the past as well. Hitting `ctrl+c` stopped the process, but I never found the underlying cause.

**Comment by andreashager** [comment]
I have the issue with every Terminal in Windows 10, with `CTRL + C` you can terminate as you already said 😀 Some terminals (eg. the integrated VS Code Terminal) could not be terminated with `CTRL + C` - there I have to close it and reopen it 🙈 

I just want to document it, maybe there was a simple solution 😄 But for me its oke to terminate with `CTRL + C` 😊

**Comment by garfieldius** [comment]
I tried the same version with powershell and cmd.exe and coudn't reproduce this on the same Windows version. Will investigate further.

**Comment by liayn** [comment]
Could it be that this is related to addons? 
I have: G docs offline, lighthouse, ublock origin and xdebug helper

**Comment by andreashager** [comment]
Your suggetions with extensions was the jackpot 🥳 

I disabled all my extensions - tada it works like a charm. Then I enabled the extensions one by one to find the extension which causes the hanging of the terminal.

- Chrome Apps (from Google itself)
  - Docs
  - Präsentationen
  - Tabellen
  - Google Docs Offline
- User Extensions
  - RESTED
  - Wappalyzer
  - Web Developer
  - Xdebug helper
  - Ghostery <-- this is the one which causes the hang 😞 

So the Ad Blocker is causing the hang somehow 😅

**Comment by liayn** [comment]
I suspect it is ublock then on my side

**Comment by garfieldius** [comment]
Thanks for the investigation. I will look into that.
