### ISSUE TITLE
Indentation wrong after save

### ISSUE THREAD

**Issue by garfieldius** [garfieldius/t3ll#18]
@garfieldius Is there a limitation for the indentation? In our team we have a .editorconfig file that uses 4 spaces for .xliff files instead of 3 and everytime when we save the file the indentation is set to 3 instead of keeping 4 🤔

_Originally posted by @andreashager in https://github.com/garfieldius/t3ll/issues/2#issuecomment-844906864_

**Comment by andreashager** [comment]
@garfieldius Thanks, works now 😊
