### ISSUE TITLE
datatype attribute missing

### ISSUE THREAD

**Issue by koehnlein** [garfieldius/t3ll#19]
First of all, thanks for this great tool. It really makes my life easier when adding and editing XLF files. 😀

Today I sent an XLF file to a translation agency, who unfortunately answered that they cannot open/import the file. The problem is, that the software requires the `<file>` tag to have a `datatype` attribute. 

I checked the [XLIFF 1.2 specification](https://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#Specs_Elem_TopHeader) which indeed says, that the `datatype` attribute is required:

> **3.2.1. Top-level and Header Elements**
>
> ...
>
> &lt;file&gt;
> 
> ...
> 
> Required attributes:
>
> original, source-language, datatype.

It really would be great if you could add this attribute to the generated XLF file. 👍

**Comment by liayn** [comment]
Just adding an example from current v11 TYPO3 Core:

`<file source-language="en" datatype="plaintext" original="EXT:install/Resources/Private/Language/BackendModule.xlf" date="2011-10-17T20:22:33Z" product-name="install">`
