### ISSUE TITLE
feature request: preserve indentation style

### ISSUE THREAD

**Issue by liayn** [garfieldius/t3ll#2]
Suggested editorconfig of TYPO3 core is to use tabs for xlf files.
Saving files currently changes the indentation to spaces. It would be nice, if the existing indentation style could be preserved

**Comment by andreashager** [comment]
@garfieldius Is there a limitation for the indentation? In our team we have a .editorconfig file that uses 4 spaces for .xliff files instead of 3 and everytime when we save the file the indentation is set to 3 instead of keeping 4 🤔
