### ISSUE TITLE
Increase XLIFF compliance by not dropping an empty <SOURCE>

### ISSUE THREAD

**Issue by jpmschuler** [garfieldius/t3ll#20]
I use you wonderful tool to convert XML,  ease the clean up and maintenance of the XLIFF and it is a lifesaver.
Now I tried an XLIFF linter/validator and found out that in seldom circumstances the result is not valid.

In case of an empty default label `my.label` which has a translation the result should be

`locallang.xlf`

			<trans-unit id="my.label" resname="my.label">
				<source></source>
			</trans-unit>
			
`de.locallang.xlf`

			<trans-unit id="my.label" resname="my.label">
				<source></source>
				<target>Language Override</target>
			</trans-unit>
			
			
However `t3ll` creates on edit:
`locallang.xlf`

			<trans-unit id="my.label" resname="my.label"></trans-unit>

On edit of course this won't happen to the translated file, but after conversion from XML I also got:
`de.locallang.xlf`

			<trans-unit id="my.label" resname="my.label">
				<target>Language Override</target>
			</trans-unit>
			
Both are deemed invalid, as `<source>` seems to be a necessary first subchild.

For the validating I used macOS terminal `xmllint` installed via `brew install xmlstarlet`, on linux it seems to be a default tool.

     wget -q -O xliff-core-1.2-strict.xsd https://docs.oasis-open.org/xliff/v1.2/os/xliff-core-1.2-strict.xsd
     xmllint --schema xliff-core-1.2-strict.xsd --noout $(find Resources/Private/Language -name '*.xlf'
     
I know that the behaviour for `<target>` should probably still be "drop trans-unit" and I know that it is an edge case to have an empty `<source>` label, but at least I thought to mention it, no matter how you will consider this info.
Even if it is out-of-scope because of the used libraries it is worth documenting it here IMHO.

**Comment by garfieldius** [comment]
@jpmschuler Thanks for the xmllint command. I successfully validated the generated files with v0.6.6. Please take a look when possible.

**Comment by jpmschuler** [comment]
Works perfectly now, all my wobbly edge case files can now be edited with the tool and still validate! Thx a lot!
