### ISSUE TITLE
t3ll ends prematurely on macOS - option to increase timeouts?

### ISSUE THREAD

**Issue by jpmschuler** [garfieldius/t3ll#22]
My normal behaviour on my 5 year old MacBook Pro was always like needing to run t3ll twice, e.g. 
` > t3ll Resources/Private/Language/locallang.xlf`
after about 2 secs: command exits with 0
after about 4 secs: the chrome window opens with "Connection Refused"
` > t3ll Resources/Private/Language/locallang.xlf`
as the chrome window was still open, the t3ll edit view loaded faster, thus it didn't exit with 0 and it could edit
(Sometimes, when the exit signal is near to the edit view opening it could also show the edit view with `t3ll does not seem to be running. Close and reopen this window` due to this concurrency.)

But switching projects and other tools a bit my macOS is now regularly under higher load. Sometimes even after 10 command retries I can't create a valid edit session. Knowing it is timeout and load caused, I re-schedule the xlf editing to another time to circumvent it currently.

Would it be possible to:

-  check the events so that this works better, or
-  increase the timeouts used to support poor perfomance scenarios, or just
-  make the timeout configureable (e.g. a parameter), so that fools like me running into such scenarios can just set a timeout nobody else would like

This tool is so much better than anything else, so I'll endure this, but perhaps there is an easy way to implement a fix for this

**Comment by garfieldius** [comment]
Since the start of chrome/chromium  was never reliable in the past, I switched to a different approach to find and start chrome.

Please update to v0.7.0 and check if it solves the problem.

**Comment by jpmschuler** [comment]
Wonderful! Yes indeed this resolves 100% of all hiccups experienced. 

(Sorry for the late reply, installed, went out sick for 2 weeks and forgot about it....)

**Comment by garfieldius** [comment]
@jpmschuler Thanks for the feedback. Closing this.
