### ISSUE TITLE
"no chromium or google chrome installation found" on Fedora 37

### ISSUE THREAD

**Issue by liayn** [garfieldius/t3ll#23]
I'm on KDE Plasma and installed chromium via the fedora repositories (version 111).

```
➜  ~ which chromium-browser 
/usr/bin/chromium-browser
``` 

This is not checked in https://github.com/garfieldius/t3ll/blob/main/browser/lookup_linux.go

**Comment by liayn** [comment]
I made a symlink now within ` /usr/local/bin/`  as a workaround

**Comment by garfieldius** [comment]
Switched to a different approach to find and start chrome in the new version.

Please update to v0.7.0 and check if it solves the problem.

**Comment by liayn** [comment]
Thanks! Will give it a shot tomorrow.

**Comment by liayn** [comment]
First note: Works great on Windows and even nicer: it now works as well when invoking t3ll on a file located within WSL from within git bash.

**Comment by liayn** [comment]
Works flawlessly on Fedora now too. Thanks!
