### ISSUE TITLE
Norwegian-Bokmål nb not supported

### ISSUE THREAD

**Issue by vnc-omol** [garfieldius/t3ll#25]
Hi, thanks for your tool.
The Language Norwegian-Bokmål nb is not supported?
kind regards
Ole

**Comment by garfieldius** [comment]
Hi, it's added in version [0.7.4](https://github.com/garfieldius/t3ll/releases/tag/v0.7.4). Please give it a try on occasion.

**Comment by vnc-omol** [comment]
Thank you! But: It uses now bk as language code not nb (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes#nb)

**Comment by garfieldius** [comment]
Hi, updated in [0.7.5](https://github.com/garfieldius/t3ll/releases/tag/v0.7.5) please give it a try.

**Comment by vnc-omol** [comment]
Looks good, works great. Thanks alot!
