### ISSUE TITLE
Could not open locallang files (Infinite loop)

### ISSUE THREAD

**Issue by andreashager** [garfieldius/t3ll#26]
We have a problem opening language files - I saw that you add the -d flag to the new release so i tried it 🙂

The process hangs with an infinite loop at:

![grafik](https://github.com/garfieldius/t3ll/assets/3351175/0e667598-1aaf-4c6a-b1f1-2442d71b71a8)

We don't have any ext_emconf.php Files for our projects anymore because they are not neceassary since TYPO3 v11.4 in composer based installations. If you need more information please let me know 🙂

_Originally posted by @andreashager in https://github.com/garfieldius/t3ll/issues/24#issuecomment-1663567583_

**Comment by liayn** [comment]
Confimed, we have the same issue. Thanks for the  `-d` hint.

**Comment by andreashager** [comment]
I tested it by creating an empty `ext_emconf.php` in the extension root directory and the t3ll GUI loads without any problems 🥳 So the absence of the `ext_emconf.php` file causes the infinite loop - one solution could be to first check for `ext_emconf.php` and then for  `composer.json` if the first not found. If none of the files could be found abort with an error 🤔

**Comment by garfieldius** [comment]
A fix is added in version [0.7.4](https://github.com/garfieldius/t3ll/releases/tag/v0.7.4). I was not able to reproduce this on Fedora and Windows with this version. Please check if it solves this.

**Comment by andreashager** [comment]
@garfieldius Works again! THANKS! 🥳🥳🥳🥳

@liayn Also works for you now? 🙂

**Comment by liayn** [comment]
looking good
