### ISSUE TITLE
Parameter „approved“

### ISSUE THREAD

**Issue by rtoenjes** [garfieldius/t3ll#27]
Since V12 TYPO3 only accepts so called approved (reviewed) translation strings (see [docs](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Configuration/Typo3ConfVars/SYS.html#typo3confvars-sys-lang-requireapprovedlocalizations)).
So it would be nice to have this parameter added (optionally) to the translation files by your great tool.

**Comment by garfieldius** [comment]
t3ll does not add an approved attribute by default. TYPO3 will then use "yes" as a default, see: <https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/Classes/Localization/Parser/XliffParser.php#L49>

Adding this to t3ll would allow to self-approve all labels, which contradicts the whole idea.

Details on how t3ll handles the approved property are described at <https://github.com/garfieldius/t3ll/?tab=readme-ov-file#approved-translations>
