### ISSUE TITLE
id/resname attributes can break the creation of a valid xliff file

### ISSUE THREAD

**Issue by josefglatz** [garfieldius/t3ll#29]
## How to reproduce?

1. clone TYPO3 core (13.0-dev)
2. Run `t3ll typo3/sysext/extbase/Tests/Functional/Fixtures/Extensions/blog_example/Resources/Private/Language/locallang_db.xlf`
3. Add a new translation (in my test I added `fe_users.tx_extbase_type` with content `Record Type`) after the existing string `fe_users.tx_extbase_type.TYPO3Tests\BlogExample\Domain\Model\Administrator`
4. Save

In my scenario the `<trans-unit />` of the mentioned existing was not closed anymore and the xliff was not valid anymore.

**Comment by garfieldius** [comment]
I was unable to reproduce this with the exact same source files and same label id. Is this still a problem?

**Comment by josefglatz** [comment]
Thank you! I can't reproduce it  without pulling an actual revision of TYPO3 main branch with the actual t3ll version which I updated some minutes ago via `brew upgrade`.

Thank you Georg for "fixing".

For reference: I had the problem while having checked out commit `1d86d5b4`
