### ISSUE TITLE
Extension key is not shown in header

### ISSUE THREAD

**Issue by andreashager** [garfieldius/t3ll#32]
In the Headline of t3ll there is the string EXT:Resources/.... shown but the extension is missing.

![grafik](https://github.com/garfieldius/t3ll/assets/3351175/35ecf4a9-2e69-424b-abd0-8dd509d93c68)

I would expect that there is something like EXT:extension_name/Resources/... 🙂 

Thanks for your help!

**Comment by garfieldius** [comment]
A fix for this is in [v0.7.6](https://github.com/garfieldius/t3ll/releases/tag/v0.7.6)

**Comment by josefglatz** [comment]
Works for me with mentioned version.

**Comment by andreashager** [comment]
Works for me  in the mentioned Version top 🥳🥳

Thanks for the update 😊
