### ISSUE TITLE
XML to XLIFF converter not working

### ISSUE THREAD

**Issue by josefglatz** [garfieldius/t3ll#8]
I found out that your great t3ll tool can convert XML to XLIFF. Is this feature known as not working or still WIP?

If I open a xml file (no matter if I edit or not edit a string) and click the button `Convert to XLIFF` I get a screen info "No Data changed". No additional file was added next to the xlf file.

I would be very happy if this feature does the conversion. Then you don't need another tool for this task as the upcoming TYPO3 11 has no support for XML anymore.

**Comment by garfieldius** [comment]
Fixed in 2e7230c785db9867076bf2f83918fcb0a305843d, part of v0.5.4

**Comment by josefglatz** [comment]
Thank you so much!
